linters-settings:
  govet:
    enable-all: true
  staticcheck:
    enable-all: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - unconvert
    - gofmt
    - goimports